### ISSUE TITLE
Strange errors - 

### ISSUE THREAD

**Issue by ren-kun** [StarryPy/StarryPy3k#84] opened 2017-05-21 03:51 UTC
Now It may have been fixed last commit, but I get the following errors quite often

---------------------------------

age future: <Task finished coro=<PlanetAnnouncer._announce() done, defined at /var/Server/Starbound/Starbound/wrapper/plugins/planet_announcer.py:32> exception=AttributeError("'StarryPyServer' object has no attribute 'player'",)> 
onmessage Traceback (most recent call last): 
onmessage   File "/usr/lib/python3.5/asyncio/tasks.py", line 239, in _step 
onmessage     result = coro.send(None) 
onmessage   File "/var/Server/Starbound/Starbound/wrapper/plugins/planet_announcer.py", line 44, in _announce 
onmessage     if str(p.player.location) == location and p != connection: 
onmessage AttributeError: 'StarryPyServer' object has no attribute 'player' 
onmessage 2017-05-20 23:50:17 - ERROR - starrypy # Error while trying to send message. 
onmessage Traceback (most recent call last): 
onmessage   File "server.py", line 136, in send_message 
onmessage     yield from self.raw_write(to_send) 
onmessage   File "server.py", line 144, in raw_write 
onmessage     yield from self._writer.drain() 
onmessage   File "/usr/lib/python3.5/asyncio/streams.py", line 333, in drain 
onmessage     yield from self._protocol._drain_helper() 
onmessage   File "/usr/lib/python3.5/asyncio/streams.py", line 208, in _drain_helper 
onmessage     assert waiter is None or waiter.cancelled() 
onmessage AssertionError 
onmessage 2017-05-20 23:50:17 - ERROR - starrypy #  
onmessage Traceback (most recent call last): 
onmessage   File "server.py", line 136, in send_message 
onmessage     yield from self.raw_write(to_send) 
onmessage   File "server.py", line 144, in raw_write 
onmessage     yield from self._writer.drain() 
onmessage   File "/usr/lib/python3.5/asyncio/streams.py", line 333, in drain 
onmessage     yield from self._protocol._drain_helper() 
onmessage   File "/usr/lib/python3.5/asyncio/streams.py", line 208, in _drain_helper 
onmessage     assert waiter is None or waiter.cancelled() 
onmessage AssertionError 
onmessage 2017-05-20 23:50:19 - INFO - starrypy # Rem

**Comment by GermaniumSystem** [comment] 2017-05-22 16:25
I've been seeing these for a while as well, and I think I have found the cause.  
planet_announcer.py runs through all established connections and sends a message if the connection's player is in the right location. However, it does not check if the connection actually has a player yet. If there are any open connections that have not fully logged in, like from a port scanner, it will throw an exception because it is trying to read an attribute that the connection does not have.

This may also be the cause of intermittent ship auto-claim, /here, and /modchat issues as they all use a similar technique.

I'll take a look into fixing it. If anyone wants to replicate the issue, open a connection with netcat (`nc <ip> <port>`) and log in or warp to a planet while the connection is still open.

**Comment by medeor413** [comment] 2017-05-22 17:02
I'll try and get this addressed in the next patch.

**Closed** 2017-05-30 16:24 UTC
Labels: bug
