### ISSUE TITLE
Unconfirmed: Party chat conveys to discord. 

### ISSUE THREAD

**Issue by ren-kun** [StarryPy/StarryPy3k#86] opened 2017-05-29 08:34 UTC
The discord bot transfers PARTY chat over to discord.

Is what users are telling me.

**Comment by medeor413** [comment] 2017-05-29 15:27
Couldn't reproduce this. I'm closing it for now, feel free to reopen it if it happens again.

**Closed by medeor413** 2017-05-29 15:27 UTC
