### ISSUE TITLE
Discord Bot Crashed

### ISSUE THREAD

**Issue by thunderbirdtr** [StarryPy/StarryPy3k#63] opened 2017-02-05 19:07 UTC
Hello ; After I setup everything plus discord bot, It's decide to crash and it was working before restart ? I checked syntax/codes but still kinda pointless. I didn't change anything on it 

```
Ignoring exception in on_message
Traceback (most recent call last):
  File "/.../.../..../starryp3k_main/virtualsb/lib/python3.5/site-packages/discord/client.py", line 307, in _run_event
    yield from getattr(self, event)(*args, **kwargs)
  File "/.../.../..../starryp3k_main/StarryPy3k/plugins/discord_bot.py", line 76, in on_message
    yield from DiscordPlugin.send_to_game(message)
  File "/.../.../..../starryp3k_main/StarryPy3k/plugins/discord_bot.py", line 214, in send_to_game
    asyncio.ensure_future(cls.handle_command(message.content[1:]))
TypeError: handle_command() missing 1 required positional argument: 'data'
```

PS: I shorted the paths, don't think as path issue or something

Edit1 : when put "..." to the chat makes crash when I type an actual word/letter It's not sending message but not gives error either

**Comment by ren-kun** [comment] 2017-02-06 04:51
I have to restart the server at times, as communication between Discord <-> Starbound  starts to play up.

**Comment by medeor413** [comment] 2017-02-06 16:24
Regarding that error, I've already fixed that on my fork and it will be fixed next update. Regarding the issue with the Discord bridge occasionally failing, I've not yet identified the cause of the issue there.

**Comment by medeor413** [comment] 2017-04-25 15:11
The error in this issue has been fixed, and unfortunately it looks like the issue with the bridge failing is an issue with discord.py.

**Closed by medeor413** 2017-04-25 15:11 UTC
Labels: bug
